stages:
  - compile
  - package

build-ubuntu:
  stage: compile
  image: burningdaylight/ubuntu-latest-devel
  script:
    - mkdir build-ubuntu
    - cd build-ubuntu; qmake ..; make
  artifacts:
    paths:
      - build-ubuntu/SRHDDumpReader

build-win64:
  stage: compile
  image: burningdaylight/mingw-arch:qt
  script:
    - mkdir build-win64
    - cd build-win64; x86_64-w64-mingw32-qmake-qt5 ..; make
  artifacts:
    paths:
      - build-win64/release/SRHDDumpReader.exe

build-win32:
  stage: compile
  image: burningdaylight/mingw-arch:qt
  script:
    - mkdir build-win32
    - cd build-win32; i686-w64-mingw32-qmake-qt5 ..; make
  artifacts:
    paths:
      - build-win32/release/SRHDDumpReader.exe

pack-ubuntu:
  stage: package
  image: burningdaylight/ubuntu-latest-devel
  script:
    - mkdir -p ./SRHDDumpReader
    - cp build-ubuntu/SRHDDumpReader ./SRHDDumpReader/
    - cp -r presets ./SRHDDumpReader/
    - cp ./*.json ./SRHDDumpReader/
    - cp ./Click1.wav ./SRHDDumpReader/
  artifacts:
    name: "SRHDDumpReader_linux_${CI_BUILD_REF_NAME}-${CI_BUILD_REF:0:8}"
    paths:
      - SRHDDumpReader

pack-win64:
  stage: package
  image: burningdaylight/mingw-arch:qt
  script:
    - mkdir -p ./SRHDDumpReader/platforms/
    - mkdir -p ./SRHDDumpReader/imageformats/
    - cp build-win64/release/SRHDDumpReader.exe ./SRHDDumpReader/
    - cp /usr/x86_64-w64-mingw32/bin/lib{gcc_s_seh-1,ssp-0,bz2-1,iconv-2,pcre-1,pcre2-16-0,winpthread-1,freetype-6,glib-2.0-0,intl-8,png16-16,harfbuzz-0,graphite2,stdc++-6}.dll ./SRHDDumpReader/
    - cp /usr/x86_64-w64-mingw32/bin/{zlib1,Qt5Core,Qt5Network,Qt5Multimedia,Qt5Gui,Qt5Widgets,Qt5Svg}.dll ./SRHDDumpReader/
    - cp /usr/x86_64-w64-mingw32/lib/qt/plugins/platforms/qwindows.dll ./SRHDDumpReader/platforms/
    - cp /usr/x86_64-w64-mingw32/lib/qt/plugins/imageformats/{qsvg,qico,qtiff,qjpeg}.dll ./SRHDDumpReader/imageformats/
    - cp -r presets ./SRHDDumpReader/
    - cp ./*.json ./SRHDDumpReader/
    - cp ./Click1.wav ./SRHDDumpReader/
  artifacts:
    name: "SRHDDumpReader_win64_${CI_BUILD_REF_NAME}-${CI_BUILD_REF:0:8}"
    paths:
      - SRHDDumpReader

pack-win32:
  stage: package
  image: burningdaylight/mingw-arch:qt
  script:
    - mkdir -p ./SRHDDumpReader/platforms/
    - mkdir -p ./SRHDDumpReader/imageformats/
    - cp build-win32/release/SRHDDumpReader.exe ./SRHDDumpReader/
    - cp /usr/i686-w64-mingw32/bin/lib{gcc_s_dw2-1,ssp-0,bz2-1,iconv-2,pcre-1,pcre2-16-0,winpthread-1,freetype-6,glib-2.0-0,intl-8,png16-16,harfbuzz-0,graphite2,stdc++-6}.dll ./SRHDDumpReader/ || true
    - cp /usr/i686-w64-mingw32/bin/{zlib1,Qt5Core,Qt5Network,Qt5Multimedia,Qt5Gui,Qt5Widgets,Qt5Svg}.dll ./SRHDDumpReader/
    - cp /usr/i686-w64-mingw32/lib/qt/plugins/platforms/qwindows.dll ./SRHDDumpReader/platforms/
    - cp /usr/i686-w64-mingw32/lib/qt/plugins/imageformats/{qsvg,qico,qtiff,qjpeg}.dll ./SRHDDumpReader/imageformats/
    - cp -r presets ./SRHDDumpReader/
    - cp ./*.json ./SRHDDumpReader/
    - cp ./Click1.wav ./SRHDDumpReader/
  artifacts:
    name: "SRHDDumpReader_win32_${CI_BUILD_REF_NAME}-${CI_BUILD_REF:0:8}"
    paths:
      - SRHDDumpReader
