stages:
  - compile
  - package

build-ubuntu:
  stage: compile
  image: burningdaylight/ubuntu-latest-devel
  script:
    - mkdir build-ubuntu
    - cd build-ubuntu; qmake ..; make
  artifacts:
    paths:
      - build-ubuntu/SRHDDumpReader

build-win64:
  stage: compile
  image: burningdaylight/mingw-arch:qt
  script:
    - mkdir build-win64
    - cd build-win64; x86_64-w64-mingw32-qmake-qt5 ..; make
  artifacts:
    paths:
      - build-win64/release/SRHDDumpReader.exe

build-win32:
  stage: compile
  image: burningdaylight/mingw-arch:qt
  script:
    - mkdir build-win32
    - cd build-win32; i686-w64-mingw32-qmake-qt5 ..; make
  artifacts:
    paths:
      - build-win32/release/SRHDDumpReader.exe

pack-win64:
  stage: package
  image: burningdaylight/mingw-arch:qt
  script:
    - mkdir -p ./SRHDDumpReader/platforms/
    - mkdir -p ./SRHDDumpReader/imageformats/
    - cp build-win64/release/SRHDDumpReader.exe ./SRHDDumpReader/
    - cp /usr/x86_64-w64-mingw32/bin/{libssp-0,libbz2-1,libiconv-2,libpcre-1,libwinpthread-1,Qt5Multimedia,zlib1,libfreetype-6,libglib-2.0-0,libintl-8,libpng16-16,Qt5Core,Qt5Network,libgcc_s_seh-1,libharfbuzz-0,libpcre16-0,libpcre2-16-0,libgraphite2,libstdc++-6,Qt5Gui,Qt5Widgets,Qt5Svg}.dll ./SRHDDumpReader/
    - cp /usr/x86_64-w64-mingw32/lib/qt/plugins/platforms/qwindows.dll ./SRHDDumpReader/platforms/
    - cp /usr/x86_64-w64-mingw32/lib/qt/plugins/imageformats/{qsvg,qico,qtiff,qjpeg}.dll ./SRHDDumpReader/imageformats/
    - cp -r presets ./SRHDDumpReader/
    - cp ./*.json ./SRHDDumpReader/
    - cp ./Click1.wav ./SRHDDumpReader/
  artifacts:
    name: "SRHDDumpReader_win64_${CI_BUILD_REF_NAME}-${CI_BUILD_REF:0:8}"
    paths:
      - SRHDDumpReader

pack-win32:
  stage: package
  image: burningdaylight/mingw-arch:qt
  script:
    - mkdir -p ./SRHDDumpReader/platforms/
    - mkdir -p ./SRHDDumpReader/imageformats/
    - cp build-win32/release/SRHDDumpReader.exe ./SRHDDumpReader/
    - cp /usr/i686-w64-mingw32/bin/{libssp-0,libbz2-1,libiconv-2,libpcre-1,libwinpthread-1,Qt5Multimedia,zlib1,libfreetype-6,libglib-2.0-0,libintl-8,libpng16-16,Qt5Core,Qt5Network,libgcc_s_sjlj-1,libharfbuzz-0,libpcre16-0,libpcre2-16-0,libgraphite2,libstdc++-6,Qt5Gui,Qt5Widgets,Qt5Svg}.dll ./SRHDDumpReader/
    - cp /usr/i686-w64-mingw32/lib/qt/plugins/platforms/qwindows.dll ./SRHDDumpReader/platforms/
    - cp /usr/i686-w64-mingw32/lib/qt/plugins/imageformats/{qsvg,qico,qtiff,qjpeg}.dll ./SRHDDumpReader/imageformats/
    - cp -r presets ./SRHDDumpReader/
    - cp ./*.json ./SRHDDumpReader/
    - cp ./Click1.wav ./SRHDDumpReader/
  artifacts:
    name: "SRHDDumpReader_win32_${CI_BUILD_REF_NAME}-${CI_BUILD_REF:0:8}"
    paths:
      - SRHDDumpReader
